#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  ## Redis 配置

  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 47.98.187.229
    ## Redis服务器连接端口
    port: 6379
    ## 密码（默认为空）
    password:

    ## 连接池配置
    pool:
      ## 连接池最大连接数
      max-active: 8
      max-wait: -1
      min-idle: 0

## Mybatis 配置
mybatis:
  type-aliases-package: com.spring.springboot.domain
  mapper-locations: classpath:mapper/*.xml

## Log输出
logging:
  path: /log
  file: springboot-redis.log
